services:
  - docker
dist: xenial
before_install:
  - docker build -t decrypt/crypto/cd-dev -f Dockerfile-dev .
  - docker-compose -f docker-compose-test.yml up --abort-on-container-exit
# script:
# - docker build -t decrypt/crypto/cd-dev -f Dockerfile-dev .
# - docker-compose -f docker-compose-test.yml up --abort-on-container-exit

# env:
#   global:
#     - PATH=/opt/python/3.7.1/bin:$PATH
