services:
  - docker

dist: xenial

before_script:
  - pip install --upgrade pip
  - pip install docker-compose
  - docker build -t decrypt/crypto/cd-dev -f Dockerfile-dev .
# before_install:
#   - docker build -t decrypt/crypto/cd-dev -f Dockerfile-dev .
#   - docker-compose -f docker-compose-test.yml up --abort-on-container-exit
script:
  - docker-compose -f docker-compose-test.yml up --abort-on-container-exit
  - python3 -VV
  - pip -V
# env:
#   global:
#     - PATH=/opt/python/3.7.1/bin:$PATH
